import type { CatalogExercise } from '@/domain/engine';

/** Tipo extendido para UI: descripción, tips, músculos, dificultad y categoría. Compatible con CatalogExercise. */
export interface CatalogExerciseExtended extends CatalogExercise {
  description: string;
  tips: string[];
  muscles: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  category: 'compound' | 'isolation' | 'cardio' | 'core';
}

export const EXERCISE_CATALOG: CatalogExerciseExtended[] = [
  // —— PECHO ——
  {
    id: 'bench_press',
    name: 'Press banca',
    muscleGroup: 'pectorales',
    description: 'Acostado en banca, baja la barra al pecho y empuja hasta extender los codos manteniendo los omóplatos retraídos.',
    tips: ['Mantén los pies apoyados y glúteos en la banca.', 'No rebotes la barra en el pecho.', 'Controla la bajada 2–3 segundos.'],
    muscles: ['Pectoral mayor', 'Deltoides anterior', 'Tríceps'],
    difficulty: 'beginner',
    category: 'compound',
  },
  {
    id: 'incline_barbell_press',
    name: 'Press inclinado con barra',
    muscleGroup: 'pectorales',
    description: 'Press en banca inclinada (30–45°) para enfatizar la porción clavicular del pectoral.',
    tips: ['Banca entre 30° y 45° para mayor activación superior.', 'Apoya bien la espalda y no arquees en exceso.', 'Baja la barra hacia la parte alta del pecho.'],
    muscles: ['Pectoral superior (clavicular)', 'Deltoides anterior', 'Tríceps'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'incline_dumbbell',
    name: 'Press inclinado con mancuernas',
    muscleGroup: 'pectorales',
    description: 'Mismo patrón que el press inclinado con barra, con mayor rango y estabilización por el uso de mancuernas.',
    tips: ['Rota las muñecas al subir para un mejor pico de contracción.', 'No dejes que los codos bajen por debajo de los hombros.', 'Mantén las mancuernas alineadas con el pecho.'],
    muscles: ['Pectoral superior', 'Deltoides anterior', 'Tríceps'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'chest_fly',
    name: 'Aperturas con mancuernas',
    muscleGroup: 'pectorales',
    description: 'Acostado, abre los brazos en arco hasta sentir el estiramiento del pecho y cierra con control.',
    tips: ['Mantén una ligera flexión de codo durante todo el movimiento.', 'No uses peso excesivo para no forzar el hombro.', 'Exhala al cerrar y contrae el pectoral.'],
    muscles: ['Pectoral mayor', 'Serrato anterior'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'cable_fly',
    name: 'Aperturas en polea',
    muscleGroup: 'pectorales',
    description: 'Aperturas con poleas (alta o cruzada) para mantener tensión constante en todo el rango.',
    tips: ['Cruza ligeramente las manos al cerrar para mayor contracción.', 'Mantén el torso estable y no balancees.', 'Ajusta la altura de las poleas según la zona a enfatizar.'],
    muscles: ['Pectoral mayor', 'Serrato anterior'],
    difficulty: 'intermediate',
    category: 'isolation',
  },
  {
    id: 'dips_chest',
    name: 'Fondos en paralelas (pecho)',
    muscleGroup: 'pectorales',
    description: 'Sujeto a las paralelas, baja el cuerpo flexionando codos hasta que los hombros queden a la altura de los codos y sube.',
    tips: ['Inclina el torso hacia delante para enfatizar pecho.', 'No bajes más allá de 90° en el codo si duele el hombro.', 'Mantén los codos ligeramente abiertos.'],
    muscles: ['Pectoral mayor', 'Tríceps', 'Deltoides anterior'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'push_ups',
    name: 'Flexiones',
    muscleGroup: 'pectorales',
    description: 'En plancha, baja el pecho hacia el suelo flexionando codos y empuja hasta extender los brazos.',
    tips: ['Mantén el core tenso y la línea recta de cabeza a talones.', 'Las manos algo más abiertas que la anchura de hombros.', 'No dejes que las caderas suban o bajen.'],
    muscles: ['Pectoral mayor', 'Tríceps', 'Deltoides anterior', 'Core'],
    difficulty: 'beginner',
    category: 'compound',
  },
  {
    id: 'pullover',
    name: 'Pullover',
    muscleGroup: 'pectorales',
    description: 'Acostado con una mancuerna o barra, lleva el peso desde encima del pecho hacia atrás por encima de la cabeza en arco.',
    tips: ['Mantén los codos con una flexión ligera y estable.', 'No uses un peso que te obligue a arquear la espalda en exceso.', 'Siente el estiramiento en el pectoral y la contracción al volver.'],
    muscles: ['Pectoral mayor', 'Dorsales', 'Serrato anterior'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'decline_bench_press',
    name: 'Press declinado',
    muscleGroup: 'pectorales',
    description: 'Press en banca declinada para enfatizar la porción inferior del pectoral.',
    tips: ['Asegura los pies y no deslices por la banca.', 'Baja la barra hacia la parte baja del esternón.', 'Evita pesos muy altos si tienes problemas de tensión en hombros.'],
    muscles: ['Pectoral inferior', 'Deltoides anterior', 'Tríceps'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  // —— ESPALDA ——
  {
    id: 'deadlift',
    name: 'Peso muerto',
    muscleGroup: 'espalda',
    description: 'De pie con la barra en el suelo, empuja con las piernas y extiende cadera y espalda para levantar la barra hasta quedar erguido.',
    tips: ['Mantén la barra pegada al cuerpo durante todo el movimiento.', 'No redondees la espalda baja; pecho alto.', 'Bloquea con la cadera al final, no hiperextiendas la lumbar.'],
    muscles: ['Espalda baja', 'Trapecio', 'Dorsales', 'Isquiotibiales', 'Glúteos', 'Cuádriceps'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'barbell_row',
    name: 'Remo con barra',
    muscleGroup: 'espalda',
    description: 'Inclinado con la barra colgando, lleva la barra hacia el abdomen retrayendo omóplatos y flexionando codos.',
    tips: ['Mantén el torso estable; evita balancear el cuerpo.', 'Lleva los codos hacia atrás, no solo las manos.', 'Aprieta el dorsal al final del movimiento.'],
    muscles: ['Dorsales', 'Trapecio', 'Romboides', 'Bíceps', 'Espalda baja'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'dumbbell_row',
    name: 'Remo con mancuerna',
    muscleGroup: 'espalda',
    description: 'Apoyado con una mano y una rodilla, lleva la mancuerna desde el brazo extendido hacia la cadera.',
    tips: ['Mantén la espalda neutra y el cuello alineado.', 'Sube el codo hacia atrás, no rotes el torso.', 'Baja con control hasta estirar el brazo.'],
    muscles: ['Dorsales', 'Trapecio', 'Romboides', 'Bíceps'],
    difficulty: 'beginner',
    category: 'compound',
  },
  {
    id: 'lat_pulldown',
    name: 'Jalón al pecho',
    muscleGroup: 'espalda',
    description: 'Sentado en la polea, tira de la barra hacia el pecho o la nuca retrayendo omóplatos y flexionando codos.',
    tips: ['Inclina ligeramente el torso hacia atrás sin balancearte.', 'Lleva los codos hacia abajo y atrás, no solo las manos.', 'No uses el impulso del cuerpo para bajar el peso.'],
    muscles: ['Dorsales', 'Trapecio', 'Bíceps', 'Hombros posteriores'],
    difficulty: 'beginner',
    category: 'compound',
  },
  {
    id: 'cable_row',
    name: 'Remo en polea',
    muscleGroup: 'espalda',
    description: 'Sentado frente a la polea, tira del agarre hacia el abdomen retrayendo omóplatos y manteniendo el torso estable.',
    tips: ['Mantén el pecho alto y no redondees los hombros.', 'Lleva el agarre hacia el ombligo o un poco más abajo.', 'Siente la contracción entre los omóplatos.'],
    muscles: ['Dorsales', 'Trapecio', 'Romboides', 'Bíceps'],
    difficulty: 'beginner',
    category: 'compound',
  },
  {
    id: 'pull_ups',
    name: 'Dominadas',
    muscleGroup: 'espalda',
    description: 'Colgado de una barra con agarre prono, sube el cuerpo hasta que la barbilla supere la barra y baja con control.',
    tips: ['Inicia con los omóplatos retraídos y deprimidos.', 'Evita balancearte; sube en línea recta.', 'Baja hasta estirar por completo los brazos.'],
    muscles: ['Dorsales', 'Trapecio', 'Bíceps', 'Core'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'hyperextension',
    name: 'Hiperextensiones',
    muscleGroup: 'espalda',
    description: 'En el banco de hiperextensiones, baja el torso con control y sube extendiendo la cadera y la espalda.',
    tips: ['No hiperextiendas el cuello; mira al frente o ligeramente abajo.', 'Cruza los brazos en el pecho o lleva un disco ligero.', 'Sube hasta quedar en línea con las piernas.'],
    muscles: ['Espalda baja', 'Glúteos', 'Isquiotibiales'],
    difficulty: 'beginner',
    category: 'compound',
  },
  {
    id: 't_bar_row',
    name: 'Remo en T',
    muscleGroup: 'espalda',
    description: 'Sobre la barra en T, tira del agarre hacia el pecho manteniendo la espalda estable.',
    tips: ['Mantén el torso inclinado y estable durante todo el movimiento.', 'Lleva los codos hacia atrás cerca del cuerpo.', 'No uses solo los brazos; enfoca en dorsales y romboides.'],
    muscles: ['Dorsales', 'Trapecio', 'Romboides', 'Bíceps'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'chin_ups',
    name: 'Dominadas supinas',
    muscleGroup: 'espalda',
    description: 'Como las dominadas pero con agarre supino (palmas hacia ti), subiendo hasta superar la barra con la barbilla.',
    tips: ['Mantén el core tenso para evitar balanceo.', 'Enfoca en llevar los codos hacia atrás.', 'Baja hasta estirar completamente los brazos.'],
    muscles: ['Dorsales', 'Bíceps', 'Trapecio'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'straight_arm_pulldown',
    name: 'Jalón con brazos rectos',
    muscleGroup: 'espalda',
    description: 'De pie frente a la polea alta, baja la barra o la cuerda con los brazos casi rectos hasta la parte alta de los muslos.',
    tips: ['Mantén una ligera flexión de codo para no forzar la articulación.', 'El movimiento sale de los hombros, no de los codos.', 'Siente el estiramiento del dorsal al subir.'],
    muscles: ['Dorsales', 'Serrato anterior', 'Core'],
    difficulty: 'intermediate',
    category: 'isolation',
  },
  // —— HOMBROS ——
  {
    id: 'overhead_press',
    name: 'Press militar',
    muscleGroup: 'hombros',
    description: 'De pie o sentado, empuja la barra o mancuernas desde la altura de los hombros hasta extender los brazos por encima de la cabeza.',
    tips: ['Mantén el core tenso y no arquees la espalda en exceso.', 'La barra debe subir en línea recta; evita que se vaya hacia delante.', 'Bloquea con control al extender los codos.'],
    muscles: ['Deltoides', 'Trapecio', 'Tríceps', 'Serrato anterior'],
    difficulty: 'beginner',
    category: 'compound',
  },
  {
    id: 'lateral_raise',
    name: 'Elevaciones laterales',
    muscleGroup: 'hombros',
    description: 'De pie con mancuernas a los lados, eleva los brazos lateralmente hasta la altura de los hombros con una ligera flexión de codo.',
    tips: ['No balancees el cuerpo; sube solo con los hombros.', 'Mantén las palmas hacia abajo o ligeramente hacia delante.', 'Baja con control; no dejes caer el peso.'],
    muscles: ['Deltoides lateral'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'front_raise',
    name: 'Elevaciones frontales',
    muscleGroup: 'hombros',
    description: 'Con mancuernas o barra al frente, eleva los brazos hasta la altura de los hombros manteniendo los codos ligeramente flexionados.',
    tips: ['No uses impulso; sube y baja con control.', 'Alterna brazos o haz ambos a la vez según preferencia.', 'No superes la altura de los hombros para evitar sobrecarga.'],
    muscles: ['Deltoides anterior', 'Pectoral superior'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'reverse_fly',
    name: 'Pájaros / elevaciones posteriores',
    muscleGroup: 'hombros',
    description: 'Inclinado o en máquina, abre los brazos hacia atrás llevando los codos hacia atrás para trabajar la parte posterior del hombro.',
    tips: ['Mantén una ligera flexión de codo durante todo el movimiento.', 'No uses peso excesivo; prioriza la contracción.', 'Retrae los omóplatos al final del movimiento.'],
    muscles: ['Deltoides posterior', 'Trapecio', 'Romboides'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'face_pull',
    name: 'Face pull',
    muscleGroup: 'hombros',
    description: 'Con la cuerda en la polea a la altura de la cara, tira hacia ti separando las manos y llevando los codos hacia atrás y afuera.',
    tips: ['Mantén el torso estable y no te balancees.', 'Lleva las manos hacia las orejas, no hacia el cuello.', 'Aprieta los hombros posteriores al final.'],
    muscles: ['Deltoides posterior', 'Trapecio', 'Romboides', 'Bíceps'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'arnold_press',
    name: 'Press Arnold',
    muscleGroup: 'hombros',
    description: 'Sentado con mancuernas frente a la cara, empuja rotando las palmas de dentro hacia afuera hasta extender los brazos.',
    tips: ['Controla la rotación durante todo el movimiento.', 'No dejes que los codos se vayan hacia atrás al inicio.', 'Sube en línea recta por encima de la cabeza.'],
    muscles: ['Deltoides (anterior, lateral y posterior)', 'Tríceps'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'upright_row',
    name: 'Remo al mentón',
    muscleGroup: 'hombros',
    description: 'De pie con la barra o mancuernas, tira del peso hacia el mentón elevando los codos por los lados.',
    tips: ['No subas la barra más allá del esternón para cuidar el hombro.', 'Los codos deben ir por encima de las manos.', 'Evita balancear el cuerpo.'],
    muscles: ['Deltoides lateral', 'Trapecio', 'Bíceps'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'cable_lateral_raise',
    name: 'Elevaciones laterales en polea',
    muscleGroup: 'hombros',
    description: 'Lateral a la polea baja, eleva el brazo hacia el lado hasta la altura del hombro manteniendo tensión constante.',
    tips: ['Mantén el torso estable; no gires hacia la polea.', 'Siente la tensión en el deltoides lateral en todo el rango.', 'Baja con control hasta estirar el brazo.'],
    muscles: ['Deltoides lateral'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  // —— BÍCEPS ——
  {
    id: 'barbell_curl',
    name: 'Curl con barra',
    muscleGroup: 'bíceps',
    description: 'De pie con la barra en agarre supino, flexiona los codos llevando la barra hacia los hombros sin balancear el cuerpo.',
    tips: ['Mantén los codos pegados al cuerpo y no los muevas hacia delante.', 'No uses impulso; sube y baja con control.', 'Extiende por completo el brazo al bajar sin bloquear.'],
    muscles: ['Bíceps', 'Braquial', 'Antebrazo'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'dumbbell_curl',
    name: 'Curl con mancuerna',
    muscleGroup: 'bíceps',
    description: 'Con mancuernas a los lados, flexiona los codos llevando las mancuernas hacia los hombros en supinación.',
    tips: ['Puedes hacer ambos brazos a la vez o alternos.', 'Rota la muñeca (supinación) al subir para mayor contracción.', 'Mantén los codos fijos al lado del cuerpo.'],
    muscles: ['Bíceps', 'Braquial', 'Antebrazo'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'hammer_curl',
    name: 'Curl martillo',
    muscleGroup: 'bíceps',
    description: 'Con mancuernas y agarre neutro (palmas hacia el cuerpo), flexiona los codos llevando las mancuernas hacia los hombros.',
    tips: ['Mantén las palmas enfrentadas durante todo el movimiento.', 'No balancees el cuerpo; aísla el brazo.', 'Baja hasta estirar el brazo sin bloquear.'],
    muscles: ['Braquial', 'Bíceps', 'Antebrazo'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'concentration_curl',
    name: 'Curl concentrado',
    muscleGroup: 'bíceps',
    description: 'Sentado con el codo apoyado en el muslo interno, flexiona el codo llevando la mancuerna hacia el hombro.',
    tips: ['El codo debe quedar fijo contra el muslo.', 'No uses el otro brazo para impulsar.', 'Contrae el bíceps al final del movimiento.'],
    muscles: ['Bíceps'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'cable_curl',
    name: 'Curl en polea',
    muscleGroup: 'bíceps',
    description: 'De pie frente a la polea baja con barra o agarre, flexiona los codos llevando las manos hacia los hombros.',
    tips: ['Mantén tensión constante gracias a la polea.', 'No te separes de la máquina para no perder tensión.', 'Controla la bajada; no dejes que el peso tire.'],
    muscles: ['Bíceps', 'Braquial'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'preacher_curl',
    name: 'Curl en banco Scott',
    muscleGroup: 'bíceps',
    description: 'Con los brazos apoyados en el banco inclinado, flexiona los codos llevando la barra o mancuernas hacia arriba.',
    tips: ['No despegues los brazos del apoyo para no traicionar el movimiento.', 'Baja con control hasta estirar sin hiperextender.', 'Evita balancear el peso.'],
    muscles: ['Bíceps', 'Braquial'],
    difficulty: 'intermediate',
    category: 'isolation',
  },
  {
    id: 'incline_dumbbell_curl',
    name: 'Curl en banco inclinado',
    muscleGroup: 'bíceps',
    description: 'Sentado en banco inclinado con mancuernas, flexiona los codos llevando las mancuernas hacia los hombros.',
    tips: ['El ángulo del banco estira más el bíceps al inicio.', 'Mantén los codos alineados con el cuerpo.', 'Baja hasta sentir un buen estiramiento.'],
    muscles: ['Bíceps', 'Braquial'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  // —— TRÍCEPS ——
  {
    id: 'tricep_pushdown',
    name: 'Extensiones de tríceps en polea',
    muscleGroup: 'tríceps',
    description: 'De pie frente a la polea alta, empuja la barra o cuerda hacia abajo extendiendo los codos manteniendo los brazos pegados al cuerpo.',
    tips: ['No separes los codos del cuerpo; el movimiento es solo en el codo.', 'Baja hasta extender por completo y sube con control.', 'Mantén el torso estable.'],
    muscles: ['Tríceps'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'french_press',
    name: 'Press francés',
    muscleGroup: 'tríceps',
    description: 'Acostado con la barra o mancuernas sobre la frente, flexiona y extiende los codos sin mover los brazos.',
    tips: ['Mantén los codos apuntando al techo y no se abran.', 'Baja hasta la frente o detrás de la cabeza con control.', 'No uses peso que te obligue a arquear la espalda.'],
    muscles: ['Tríceps'],
    difficulty: 'intermediate',
    category: 'isolation',
  },
  {
    id: 'tricep_dips',
    name: 'Fondos de tríceps',
    muscleGroup: 'tríceps',
    description: 'En paralelas o en un banco, baja el cuerpo flexionando los codos y sube extendiendo los brazos manteniendo el torso vertical.',
    tips: ['Mantén el torso lo más vertical posible para enfatizar tríceps.', 'No bajes más allá de 90° si sientes molestia en el hombro.', 'Los codos van hacia atrás, no hacia los lados.'],
    muscles: ['Tríceps', 'Deltoides anterior'],
    difficulty: 'beginner',
    category: 'compound',
  },
  {
    id: 'tricep_kickback',
    name: 'Patada de tríceps',
    muscleGroup: 'tríceps',
    description: 'Inclinado con el brazo flexionado, extiende el codo llevando la mancuerna hacia atrás hasta alinear el brazo.',
    tips: ['Mantén el brazo superior paralelo al suelo al extender.', 'No balancees; aísla el tríceps.', 'Contrae al final del movimiento.'],
    muscles: ['Tríceps'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'close_grip_bench',
    name: 'Press banca cerrado',
    muscleGroup: 'tríceps',
    description: 'Como el press banca pero con las manos más juntas; baja la barra al esternón y empuja extendiendo los codos.',
    tips: ['Las manos a la anchura de los hombros o un poco menos.', 'Mantén los codos cerca del cuerpo al bajar.', 'No dejes que las muñecas se doblen hacia atrás.'],
    muscles: ['Tríceps', 'Pectoral', 'Deltoides anterior'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'overhead_tricep_extension',
    name: 'Extensión de tríceps por encima de la cabeza',
    muscleGroup: 'tríceps',
    description: 'De pie o sentado, con una mancuerna o barra por encima de la cabeza, flexiona y extiende los codos sin mover los brazos.',
    tips: ['Mantén los codos apuntando al techo.', 'Baja con control detrás de la cabeza.', 'No arquees la espalda en exceso.'],
    muscles: ['Tríceps'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  // —— PIERNAS ——
  {
    id: 'squat',
    name: 'Sentadilla',
    muscleGroup: 'piernas',
    description: 'De pie con la barra sobre la espalda, flexiona cadera y rodillas bajando hasta que los muslos queden al menos paralelos al suelo y sube.',
    tips: ['Mantén el pecho alto y la espalda neutra.', 'Las rodillas deben seguir la línea de los pies.', 'Empuja con todo el pie, no solo los talones.'],
    muscles: ['Cuádriceps', 'Glúteos', 'Isquiotibiales', 'Core'],
    difficulty: 'beginner',
    category: 'compound',
  },
  {
    id: 'leg_press',
    name: 'Prensa de piernas',
    muscleGroup: 'piernas',
    description: 'Sentado en la prensa, empuja la plataforma con los pies hasta extender las piernas (sin bloquear) y baja con control.',
    tips: ['Coloca los pies según quieras enfatizar cuádriceps o glúteos.', 'No bloquees las rodillas al subir.', 'Baja hasta un ángulo de 90° o un poco más en rodilla.'],
    muscles: ['Cuádriceps', 'Glúteos', 'Isquiotibiales'],
    difficulty: 'beginner',
    category: 'compound',
  },
  {
    id: 'leg_extension',
    name: 'Extensión de cuádriceps',
    muscleGroup: 'piernas',
    description: 'Sentado en la máquina, extiende las piernas elevando el rodillo hasta alinear las rodillas y baja con control.',
    tips: ['No uses impulso; sube y baja con control.', 'No hiperextiendas las rodillas al final.', 'Ajusta el respaldo para que la rodilla coincida con el eje del aparato.'],
    muscles: ['Cuádriceps'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'leg_curl',
    name: 'Curl femoral',
    muscleGroup: 'piernas',
    description: 'Tumbado o sentado en la máquina, flexiona las rodillas llevando el rodillo hacia los glúteos y baja con control.',
    tips: ['Mantén las caderas apoyadas; no las levantes al subir.', 'Contrae los isquiotibiales al final del movimiento.', 'Baja sin dejar que el peso descanse.'],
    muscles: ['Isquiotibiales'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'romanian_deadlift',
    name: 'Peso muerto rumano',
    muscleGroup: 'piernas',
    description: 'Con la barra o mancuernas, flexiona la cadera llevando el peso hacia el suelo manteniendo las piernas casi rectas y vuelve a la vertical.',
    tips: ['Mantén una ligera flexión de rodilla; no bloquees.', 'Siente el estiramiento en isquiotibiales y glúteos.', 'No redondees la espalda; pecho alto.'],
    muscles: ['Isquiotibiales', 'Glúteos', 'Espalda baja'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'lunges',
    name: 'Zancadas',
    muscleGroup: 'piernas',
    description: 'De pie, da un paso al frente y baja hasta que ambas rodillas formen unos 90°, luego empuja para volver y repite.',
    tips: ['Mantén el torso vertical; no te inclines hacia delante.', 'La rodilla delantera no debe pasar del pie.', 'Puedes hacer en sitio o caminando.'],
    muscles: ['Cuádriceps', 'Glúteos', 'Isquiotibiales'],
    difficulty: 'beginner',
    category: 'compound',
  },
  {
    id: 'hip_thrust',
    name: 'Hip thrust',
    muscleGroup: 'piernas',
    description: 'Con la espalda alta apoyada en un banco y la barra sobre la cadera, extiende la cadera empujando hacia arriba hasta alinear torso y muslos.',
    tips: ['Mantén la barbilla metida y no hiperextiendas el cuello.', 'Empuja con los talones y aprieta glúteos al tope.', 'La barra debe apoyar sobre la cadera, no sobre el hueso.'],
    muscles: ['Glúteos', 'Isquiotibiales', 'Core'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'calf_raise',
    name: 'Elevación de talones',
    muscleGroup: 'piernas',
    description: 'De pie o sentado, eleva los talones empujando con la punta del pie y baja con control hasta sentir estiramiento en la pantorrilla.',
    tips: ['Haz una pausa arriba y abajo para mayor trabajo.', 'Puedes hacerlo con peso corporal, barra o máquina.', 'No rebotes; controla todo el rango.'],
    muscles: ['Gemelos', 'Sóleo'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  {
    id: 'hack_squat',
    name: 'Sentadilla hack',
    muscleGroup: 'piernas',
    description: 'En la máquina hack, con la espalda apoyada en la plataforma, baja flexionando rodillas y sube empujando con las piernas.',
    tips: ['Los pies pueden ir más adelante o atrás para cambiar el énfasis.', 'Mantén la espalda pegada al respaldo.', 'Baja hasta al menos 90° en la rodilla.'],
    muscles: ['Cuádriceps', 'Glúteos'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Sentadilla búlgara',
    muscleGroup: 'piernas',
    description: 'Con el pie trasero elevado en un banco, baja la pierna delantera hasta que el muslo quede paralelo al suelo y sube.',
    tips: ['Mantén el torso lo más vertical posible.', 'La rodilla delantera no debe pasar mucho del pie.', 'Puedes usar mancuernas o barra.'],
    muscles: ['Cuádriceps', 'Glúteos', 'Isquiotibiales'],
    difficulty: 'intermediate',
    category: 'compound',
  },
  {
    id: 'goblet_squat',
    name: 'Sentadilla tipo copa',
    muscleGroup: 'piernas',
    description: 'Sujetando una mancuerna o kettlebell frente al pecho, realiza una sentadilla manteniendo los codos dentro de las rodillas.',
    tips: ['Mantén el peso cerca del pecho y los codos altos.', 'Empuja las rodillas hacia fuera contra los codos.', 'Baja hasta que los muslos pasen de paralelo si tu movilidad lo permite.'],
    muscles: ['Cuádriceps', 'Glúteos', 'Core'],
    difficulty: 'beginner',
    category: 'compound',
  },
  {
    id: 'seated_calf_raise',
    name: 'Elevación de talones sentado',
    muscleGroup: 'piernas',
    description: 'Sentado en la máquina con las puntas de los pies en la plataforma, eleva los talones y baja con control.',
    tips: ['Enfoca más en el sóleo que la variante de pie.', 'Haz una pausa en la contracción máxima.', 'Baja hasta sentir un buen estiramiento.'],
    muscles: ['Sóleo', 'Gemelos'],
    difficulty: 'beginner',
    category: 'isolation',
  },
  // —— CORE ——
  {
    id: 'plank',
    name: 'Plancha',
    muscleGroup: 'core',
    description: 'En posición de flexión apoyado sobre antebrazos y puntas de los pies, mantén el cuerpo en línea recta sin dejar caer la cadera.',
    tips: ['Mantén el core tenso y no arquees la espalda.', 'Mira al suelo para mantener la columna neutra.', 'Respira con normalidad; no aguantes la respiración.'],
    muscles: ['Recto abdominal', 'Transverso', 'Oblicuos', 'Core'],
    difficulty: 'beginner',
    category: 'core',
  },
  {
    id: 'crunch',
    name: 'Crunch / abdominales',
    muscleGroup: 'core',
    description: 'Acostado con las piernas flexionadas, despega los hombros del suelo curando la espalda y contrae el abdomen.',
    tips: ['No tires del cuello; las manos solo apoyan la cabeza.', 'Despega hombros y parte alta de espalda, no todo el torso.', 'Exhala al subir y contrae el abdomen.'],
    muscles: ['Recto abdominal'],
    difficulty: 'beginner',
    category: 'core',
  },
  {
    id: 'reverse_crunch',
    name: 'Crunch inverso',
    muscleGroup: 'core',
    description: 'Acostado con las piernas elevadas y rodillas flexionadas, lleva las rodillas hacia el pecho despegando la cadera del suelo.',
    tips: ['No balancees las piernas; usa el abdomen para subir.', 'Mantén la parte alta de la espalda en el suelo.', 'Baja con control sin dejar caer las piernas de golpe.'],
    muscles: ['Recto abdominal', 'Transverso'],
    difficulty: 'beginner',
    category: 'core',
  },
  {
    id: 'ab_wheel',
    name: 'Rueda abdominal',
    muscleGroup: 'core',
    description: 'De rodillas o de pie, rueda la rueda hacia delante extendiendo el cuerpo y vuelve con control contrayendo el core.',
    tips: ['No dejes que la cadera caiga; mantén el core tenso.', 'Empieza de rodillas si de pie es demasiado difícil.', 'Vuelve contrayendo el abdomen, no solo con los brazos.'],
    muscles: ['Recto abdominal', 'Transverso', 'Oblicuos'],
    difficulty: 'intermediate',
    category: 'core',
  },
  {
    id: 'leg_raise',
    name: 'Elevación de piernas',
    muscleGroup: 'core',
    description: 'Colgado de una barra o en banco, eleva las piernas (rectas o flexionadas) hacia arriba hasta que las caderas se flexionen.',
    tips: ['No balancees el cuerpo; sube con el abdomen.', 'Puedes flexionar las rodillas para facilitar al inicio.', 'Baja con control sin balancear.'],
    muscles: ['Recto abdominal', 'Transverso', 'Flexores de cadera'],
    difficulty: 'intermediate',
    category: 'core',
  },
  {
    id: 'russian_twist',
    name: 'Oblicuos / Russian twist',
    muscleGroup: 'core',
    description: 'Sentado con el torso inclinado hacia atrás, gira el torso de lado a lado tocando el suelo o un peso a cada lado.',
    tips: ['Mantén el core tenso y no te apoyes solo en los glúteos.', 'El movimiento sale del torso, no de los brazos.', 'Puedes usar peso o solo las manos.'],
    muscles: ['Oblicuos', 'Recto abdominal', 'Transverso'],
    difficulty: 'beginner',
    category: 'core',
  },
  {
    id: 'dead_bug',
    name: 'Dead bug',
    muscleGroup: 'core',
    description: 'Acostado boca arriba con brazos y piernas al aire, extiende un brazo y la pierna contraria manteniendo la espalda pegada al suelo.',
    tips: ['Mantén la espalda baja pegada al suelo en todo momento.', 'Mueve brazo y pierna opuestos de forma controlada.', 'Exhala al extender e inhala al volver.'],
    muscles: ['Transverso', 'Recto abdominal', 'Oblicuos'],
    difficulty: 'beginner',
    category: 'core',
  },
  {
    id: 'bicycle_crunch',
    name: 'Bicicleta',
    muscleGroup: 'core',
    description: 'Acostado, lleva el codo hacia la rodilla contraria alternando en un movimiento de pedaleo, despegando los hombros del suelo.',
    tips: ['No tires del cuello; las manos solo apoyan.', 'El movimiento es lento y controlado, no rápido.', 'Rota el torso para llevar codo a rodilla.'],
    muscles: ['Oblicuos', 'Recto abdominal'],
    difficulty: 'beginner',
    category: 'core',
  },
  {
    id: 'side_plank',
    name: 'Plancha lateral',
    muscleGroup: 'core',
    description: 'Apoyado sobre un antebrazo y el lateral del pie, mantén el cuerpo en línea recta de lado sin dejar caer la cadera.',
    tips: ['Mantén la cadera arriba; no la dejes caer.', 'Puedes hacer con rodilla apoyada para facilitar.', 'Mira al frente o ligeramente arriba.'],
    muscles: ['Oblicuos', 'Transverso', 'Glúteo medio'],
    difficulty: 'beginner',
    category: 'core',
  },
  {
    id: 'mountain_climbers',
    name: 'Mountain climbers',
    muscleGroup: 'core',
    description: 'En posición de plancha alta, lleva las rodillas alternativamente hacia el pecho en un movimiento de carrera.',
    tips: ['Mantén las caderas estables y no las subas.', 'Core tenso en todo momento.', 'Aumenta la velocidad progresivamente sin perder forma.'],
    muscles: ['Core', 'Flexores de cadera', 'Cuádriceps', 'Hombros'],
    difficulty: 'intermediate',
    category: 'core',
  },
  // —— CARDIO ——
  {
    id: 'burpees',
    name: 'Burpees',
    muscleGroup: 'core',
    description: 'De pie, baja a flexión, haz una flexión (opcional), lleva los pies hacia las manos y salta elevando los brazos.',
    tips: ['Mantén el core tenso durante todo el movimiento.', 'Aterriza suave para proteger rodillas y espalda.', 'Modifica saltando menos o sin flexión si es necesario.'],
    muscles: ['Cuerpo completo', 'Core', 'Piernas', 'Pecho', 'Hombros'],
    difficulty: 'intermediate',
    category: 'cardio',
  },
  {
    id: 'jump_rope',
    name: 'Salto a la comba',
    muscleGroup: 'core',
    description: 'Salta con una cuerda pasándola por debajo de los pies de forma continua, manteniendo un ritmo constante.',
    tips: ['Mantén los codos cerca del cuerpo y gira con las muñecas.', 'Salta lo justo para que pase la cuerda.', 'Aterriza con la punta del pie para reducir impacto.'],
    muscles: ['Gemelos', 'Cuádriceps', 'Core', 'Hombros'],
    difficulty: 'beginner',
    category: 'cardio',
  },
  {
    id: 'mountain_climbers_cardio',
    name: 'Mountain climbers (cardio)',
    muscleGroup: 'core',
    description: 'En plancha alta, alterna llevando las rodillas hacia el pecho a ritmo rápido para elevar la frecuencia cardíaca.',
    tips: ['Mantén las caderas bajas y estables.', 'Aumenta el ritmo progresivamente.', 'Respira de forma constante.'],
    muscles: ['Core', 'Flexores de cadera', 'Hombros'],
    difficulty: 'intermediate',
    category: 'cardio',
  },
  {
    id: 'jumping_jacks',
    name: 'Jumping jacks',
    muscleGroup: 'core',
    description: 'De pie, salta abriendo piernas y brazos a la vez y vuelve a juntarlos en un movimiento continuo.',
    tips: ['Aterriza suave con las rodillas ligeramente flexionadas.', 'Mantén un ritmo constante.', 'Brazos y piernas se mueven a la vez.'],
    muscles: ['Cuerpo completo', 'Core'],
    difficulty: 'beginner',
    category: 'cardio',
  },
  {
    id: 'step_ups',
    name: 'Step ups',
    muscleGroup: 'piernas',
    description: 'Sube y baja de un step o banco con una pierna, alternando o repitiendo con la misma antes de cambiar.',
    tips: ['Empuja con la pierna que está en el step.', 'Mantén el torso vertical.', 'Puedes usar peso o solo corporal.'],
    muscles: ['Cuádriceps', 'Glúteos', 'Isquiotibiales'],
    difficulty: 'beginner',
    category: 'cardio',
  },
  {
    id: 'high_knees',
    name: 'Rodillas altas',
    muscleGroup: 'core',
    description: 'Corriendo en sitio, eleva las rodillas hacia el pecho de forma alterna a ritmo rápido.',
    tips: ['Mantén el core tenso y el torso erguido.', 'Brazos en movimiento como al correr.', 'Aterriza con la punta del pie.'],
    muscles: ['Core', 'Flexores de cadera', 'Cuádriceps'],
    difficulty: 'beginner',
    category: 'cardio',
  },
  {
    id: 'skater_jumps',
    name: 'Saltos de patinador',
    muscleGroup: 'core',
    description: 'Salta lateralmente de un lado a otro apoyando un pie y llevando el otro hacia atrás en un movimiento de patinador.',
    tips: ['Mantén el torso ligeramente inclinado hacia delante.', 'Aterriza suave y controlado.', 'Brazos en movimiento para equilibrio y ritmo.'],
    muscles: ['Piernas', 'Glúteos', 'Core'],
    difficulty: 'intermediate',
    category: 'cardio',
  },
];
